source('https://bioconductor.org/biocLite.R')
biocLite('pcaMethods')
biocLite('HMMcopy')
biocLite("ABAData") 
biocLite("made4")
biocLite("hierGWAS")

install.packages('ggplot2')
install.packages('e1071')
install.packages('autoencoder')
install.packages('HMM')
install.packages('plsgenomics')
install.packages("e1071")
install.packages("caret")
install.packages("pROC")
install.packages("glmnet")
install.packages("kernlab")